#encoding "utf8"

A1-> Adj<gram="ед">;
S-> A1 interp(fact.Namea::not_norm);
A2-> Adj<gram="мн">;
S-> A2 interp(fact.Namea::not_norm);
A3-> Adv;
S-> A3 interp(fact.Namea::not_norm);
A4-> Verb;
S-> A4 interp(fact.Namea::not_norm);
A5-> Noun<gnc-agr[1]> Adj<gnc-agr[1]>;
S-> A5 interp(fact.Namea::not_norm);
A6-> Adj<gnc-agr[1]> Noun<gnc-agr[1],rt>;
S-> A6 interp(fact.Namea::not_norm);
A7-> Noun<gnc-agr[1]> Adv<gnc-agr[1]>;
S-> A7 interp(fact.Namea::not_norm);
A8-> Adv<gnc-agr[1]> Noun<gnc-agr[1]>;
S-> A8 interp(fact.Namea::not_norm);
A9-> Noun<gnc-agr[1]> Verb<gnc-agr[1]>;
S-> A9 interp(fact.Namea::not_norm);
A10-> Verb<gnc-agr[1]> Noun<gnc-agr[1]>;
S-> A10 interp(fact.Namea::not_norm);
A11-> "не" Verb;
S-> A11 interp(fact.Namea::not_norm);
A12-> "не" Adv;
S-> A12 interp(fact.Namea::not_norm);
A13-> Adv<gnc-agr[1]> Verb<gnc-agr[1]>;
S-> A13 interp(fact.Namea::not_norm);
A14-> Verb<gnc-agr[1]> Adv<gnc-agr[1]>;
S-> A14 interp(fact.Namea::not_norm);
A15-> Adv<gnc-agr[1]> Prep<gnc-agr[1]>;
S-> A15 interp(fact.Namea::not_norm);
A16-> Prep<gnc-agr[1]> Adv<gnc-agr[1]>;
S-> A16 interp(fact.Namea::not_norm);
A17-> Adj<gnc-agr[1]> Adv<gnc-agr[1]>;
S-> A17 interp(fact.Namea::not_norm);
A18-> Adv<gnc-agr[1]> Adj<gnc-agr[1]>;
S-> A18 interp(fact.Namea::not_norm);
A19-> Noun Adj<gnc-agr[2]> Noun<gnc-agr[2]>;
S-> A19 interp(fact.Namea::not_norm);
A20-> Noun Adj<gnc-agr[2]> Adj<gnc-agr[2]>;
S-> A20 interp(fact.Namea::not_norm);
A21-> Noun Adv Adj;
S-> A21 interp(fact.Namea::not_norm);  
A22-> Noun<gnc-agr[1]> Adj<gnc-agr[1]> Verb<gnc-agr[1]>;
S-> A22 interp(fact.Namea::not_norm);
A23-> Noun<gnc-agr[1]> Adj<gnc-agr[1]> Prep;
S-> A23 interp(fact.Namea::not_norm); 
A24-> Adj<gnc-agr[1]> Noun<gnc-agr[1]> Noun<gnc-agr[1]>;
S-> A24 interp(fact.Namea::not_norm); 
A25-> Adj<gnc-agr[2]> Noun<gnc-agr[2]> Adj<gnc-agr[2]>;
S-> A25 interp(fact.Namea::not_norm); 
A26-> Adj<gnc-agr[2]> Noun<gnc-agr[2]> Adv<gnc-agr[2]>;
S-> A26 interp(fact.Namea::not_norm);
A27-> Noun<gnc-agr[1]> Adv<gnc-agr[1]> Adv<gnc-agr[1]>;
S-> A27 interp(fact.Namea::not_norm);
A28-> Noun<gnc-agr[1]> Adv<gnc-agr[1]> Verb<gnc-agr[1]>;
S-> A28 interp(fact.Namea::not_norm);
A29-> Adv<gnc-agr[1]> Noun<gnc-agr[1]> Adv<gnc-agr[1]>;
S-> A29 interp(fact.Namea::not_norm); 
A30-> Adv<gnc-agr[2]> Noun<gnc-agr[2]> Verb<gnc-agr[2]>;
S-> A30 interp(fact.Namea::not_norm);
A31-> Noun<gnc-agr[1]> Verb<gnc-agr[1]> Noun;
S-> A31 interp(fact.Namea::not_norm);
A32-> Noun<gnc-agr[1]> Verb<gnc-agr[1]> Adj<gnc-agr[1]>; 
S-> A32 interp(fact.Namea::not_norm); 
A33-> Noun<gnc-agr[1]> Verb<gnc-agr[1]> Adv<gnc-agr[1]>;
S-> A33 interp(fact.Namea::not_norm);
A34-> Verb<gnc-agr[1]> Noun<gnc-agr[1]> Adj<gnc-agr[1]>;
S-> A34 interp(fact.Namea::not_norm);
A35-> Verb<gnc-agr[1]> Noun<gnc-agr[1]> Adv<gnc-agr[1]>;
S-> A35 interp(fact.Namea::not_norm); 
A36-> Adv<gnc-agr[3]> Verb<gnc-agr[3]> Noun<gnc-agr[3]>;
S-> A36 interp(fact.Namea::not_norm);
A37-> Verb<gnc-agr[3]> Adv<gnc-agr[3]> Noun<gnc-agr[3]>;  
S-> A37 interp(fact.Namea::not_norm);
A38-> Verb<gnc-agr[1]> Adv<gnc-agr[1]> Adj<gnc-agr[1]>;
S-> A38 interp(fact.Namea::not_norm);
A39-> Adj Adv<gnc-agr[3]> Adj<gnc-agr[3]>;
S-> A39 interp(fact.Namea::not_norm);

//S-> Adj<gnc-agr[1]> Noun<gnc-agr[1], gram="им", sp-agr[2]> Verb<rt, sp-agr[2]>;